### ISSUE TITLE
Broken Twitch highlight links

### ISSUE THREAD

**Issue by seky16** [Matse007/SpeedrunRescueScript#15]
The script creates broken links in all three output files (`remaining_downloads.json`, `twitch_highlights.json`, `twitch_highlights.txt`). It appends 5 stars to every Twitch highlight link, eg. `https://www.twitch.tv/videos/2150175503*****`. Link without the 5 stars points to correct video.

Used the windows executable v1.2.0
config:
```yml
username: "seky16"
video-folder-name: videos
download-videos: false
allow-all: false
video-quality: "best"
ignore-links-in-description: false
safe-only-pbs: false
concurrent-fragments: 1
```
